---
- name: Create .cfg files for IOS devices from CSV
  hosts: localhost
  gather_facts: False
  connection: local
  
  vars:
    csvfile: "{{ lookup('file', 'device_variables.csv') }}"
  
  tasks: 
  - name: Parse CSV To YAML
    template:
      src: "./templates/variable-template.j2"
      dest: "./config_variables.yml"
    run_once: true

  - include_vars: config_variables.yml

  - name: Create Directory for configurations
    file:
      path: ./device_configs
      state: directory

  - name: Generate Device Configurations
    template: 
      src: "./templates/config_template.j2"
      dest: "./device_configs/{{ item.switch.hostname }}.cfg"
    delegate_to: localhost
    with_items: "{{ devices }}"

  - name: Remove Inventory YML File (inv.yml) on playbook completion
    file:
     path: config_variables.yml
     state: absent